configs={
    'debug':True,
    'db':{
        'host':'127.0.0.1',
        'post':3306,
        'user':'www',
        'password':'www',
        'db':'awesome'
    },
    'session':{
        'secret':'Awesome'
    }
}